# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 09:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photo')),
                ('wid', models.IntegerField(blank=True, default=0)),
                ('name', models.CharField(blank=True, default='', max_length=16)),
                ('public', models.BooleanField(default=False)),
                ('polls', models.PositiveIntegerField(default=0)),
                ('ctime', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='poll',
            name='topic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='voting.Topic'),
        ),
        migrations.AddField(
            model_name='poll',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
