# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.Topic'),
        ),
    ]
